version: "3.9"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client-dev
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server-dev
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev
    env_file:
      - ./server/.env
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo-dev
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
