version: "3.9"

services:
  client:
    build:
      context: ./client
    container_name: client
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - server

  server:
    build:
      context: ./server
    container_name: server
    ports:
      - "5000:5000"
    restart: unless-stopped
    env_file:
      - ./server/.env
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
